apiVersion: v1
kind: Pod
metadata:
  name: mc-pod
spec:
  containers:
  - image: nginx
    name: nginx-1
    ports:
    - containerPort: 80
  - name: ubuntu
    image: ubuntu
    command: ["echo"]
    args: ["Hello World"]